var DB2 = {
    "spirits" :
            [{
                "nr": "10001",
                "artikelid": "25053",
                "varnummer": "100",
                "namn": "Braastad XO",
                "namn2": "",
                "prisinklmoms": "442.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2000-08-07",
                "slutlev": " ",
                "varugrupp": "Cognac",
                "forpackning": "Flaska",
                "forslutning": "Naturkork",
                "ursprung": "Cognac, Fine Champagne",
                "ursprunglandnamn": "Frankrike",
                "producent": "Tiffon",
                "leverantor": "Arcus Sweden AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "40%",
                "modul": "",
                "sortiment": "FS",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1001",
                "artikelid": "190719",
                "varnummer": "10",
                "namn": "Vanlig Vodka",
                "namn2": "",
                "prisinklmoms": "195.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2006-04-01",
                "slutlev": " ",
                "varugrupp": "Okryddad sprit",
                "forpackning": "Flaska",
                "forslutning": "Skruvkapsyl",
                "ursprung": "",
                "ursprunglandnamn": "Sverige",
                "producent": "Svensk Export Vodka AB",
                "leverantor": "Fondberg",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "37.5%",
                "modul": "",
                "sortiment": "FS",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1001201",
                "artikelid": "51029",
                "varnummer": "10012",
                "namn": "Dworek Vodka",
                "namn2": "",
                "prisinklmoms": "190.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2004-12-06",
                "slutlev": " ",
                "varugrupp": "Okryddad sprit",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "",
                "ursprunglandnamn": "Polen",
                "producent": "Tarpan Fabryka Likierow",
                "leverantor": "TIWA Trading AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "37.5%",
                "modul": "",
                "sortiment": "FS",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1001202",
                "artikelid": "407506",
                "varnummer": "10012",
                "namn": "Dworek Vodka",
                "namn2": "",
                "prisinklmoms": "100.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2009-10-01",
                "slutlev": " ",
                "varugrupp": "Okryddad sprit",
                "forpackning": "Flaska",
                "forslutning": "Skruvkapsyl",
                "ursprung": "",
                "ursprunglandnamn": "Polen",
                "producent": "Tarpan Fabryka Likierow",
                "leverantor": "TIWA Trading AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "37.5%",
                "modul": "",
                "sortiment": "FS",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1003802",
                "artikelid": "513291",
                "varnummer": "10038",
                "namn": "Esping Jul Bäsk",
                "namn2": "",
                "prisinklmoms": "195.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2010-11-15",
                "slutlev": " ",
                "varugrupp": "Kryddad sprit",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "",
                "ursprunglandnamn": "Sverige",
                "producent": "Symposion International",
                "leverantor": "Symposion International AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "32%",
                "modul": "",
                "sortiment": "TSS",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1004801",
                "artikelid": "733051",
                "varnummer": "10048",
                "namn": "Rhum J. M",
                "namn2": "",
                "prisinklmoms": "729.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2013-03-01",
                "slutlev": " ",
                "varugrupp": "Rom, Mörk",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "Martinique",
                "ursprunglandnamn": "Frankrike",
                "producent": "Les Heritiers Crassous de Mede",
                "leverantor": "Cask Sweden AB",
                "argang": "2001",
                "provadargang": "",
                "alkoholhalt": "46.6%",
                "modul": "T7",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1004901",
                "artikelid": "733068",
                "varnummer": "10049",
                "namn": "Rhum J.M",
                "namn2": "",
                "prisinklmoms": "1399.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2013-04-02",
                "slutlev": " ",
                "varugrupp": "Rom, Mörk",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "Martinique",
                "ursprunglandnamn": "Frankrike",
                "producent": "Les Heritiers Crassous de Mede",
                "leverantor": "Cask Sweden AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "44.8%",
                "modul": "T7",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1005001",
                "artikelid": "733084",
                "varnummer": "10050",
                "namn": "Balcones Texas",
                "namn2": "",
                "prisinklmoms": "899.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2013-03-01",
                "slutlev": " ",
                "varugrupp": "Whisky, Malt",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "",
                "ursprunglandnamn": "USA",
                "producent": "Balcones Distilling",
                "leverantor": "Cask Sweden AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "52.2%",
                "modul": "",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1005101",
                "artikelid": "733200",
                "varnummer": "10051",
                "namn": "Balcones Brimstone",
                "namn2": "",
                "prisinklmoms": "899.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2013-03-01",
                "slutlev": " ",
                "varugrupp": "Whisky, övrig",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "",
                "ursprunglandnamn": "USA",
                "producent": "Balcones Distilling",
                "leverantor": "Cask Sweden AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "53.2%",
                "modul": "",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1005201",
                "artikelid": "733236",
                "varnummer": "10052",
                "namn": "Balcones True Blue",
                "namn2": "",
                "prisinklmoms": "899.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2013-03-01",
                "slutlev": " ",
                "varugrupp": "Whisky, övrig",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "",
                "ursprunglandnamn": "USA",
                "producent": "Balcones Distilling",
                "leverantor": "Cask Sweden AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "50.2%",
                "modul": "",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1005401",
                "artikelid": "733429",
                "varnummer": "10054",
                "namn": "Linkwood",
                "namn2": "the Octave",
                "prisinklmoms": "1159.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2013-03-01",
                "slutlev": " ",
                "varugrupp": "Whisky, Malt",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "Skottland, Highlands, Speyside",
                "ursprunglandnamn": "Storbritannien",
                "producent": "Duncan Taylor Scotch Whisky",
                "leverantor": "Clydesdale AB",
                "argang": "1989",
                "provadargang": "",
                "alkoholhalt": "51.7%",
                "modul": "",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1005502",
                "artikelid": "733446",
                "varnummer": "10055",
                "namn": "Marolo",
                "namn2": "Grappa di Arneis Vigneto Renesio",
                "prisinklmoms": "481.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2013-03-01",
                "slutlev": " ",
                "varugrupp": "Grappa och Marc, Grappa",
                "forpackning": "Flaska",
                "forslutning": "Naturkork",
                "ursprung": "",
                "ursprunglandnamn": "Italien",
                "producent": "Distilleria St Teresa dei Frat",
                "leverantor": "Haugen-Gruppen AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "50%",
                "modul": "T7",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1005602",
                "artikelid": "733468",
                "varnummer": "10056",
                "namn": "Clément",
                "namn2": "Single Cask",
                "prisinklmoms": "529.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2013-04-02",
                "slutlev": " ",
                "varugrupp": "Rom, Mörk",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "Martinique",
                "ursprunglandnamn": "Frankrike",
                "producent": "Les Heritiers Crassous de Mede",
                "leverantor": "Cask Sweden AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "47.6%",
                "modul": "T7",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "101",
                "artikelid": "1",
                "varnummer": "1",
                "namn": "Renat",
                "namn2": "",
                "prisinklmoms": "203.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "1993-10-01",
                "slutlev": " ",
                "varugrupp": "Okryddad sprit",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "",
                "ursprunglandnamn": "Internationellt m\u00c3\u00a4rke",
                "producent": "Pernod Ricard",
                "leverantor": "Pernod Ricard Sweden AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "37.5%",
                "modul": "",
                "sortiment": "FS",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1010001",
                "artikelid": "817007",
                "varnummer": "10100",
                "namn": "Romano Levi",
                "namn2": "Mostaco d\u00c2\u00b4Asti Donna Selvatica",
                "prisinklmoms": "790.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2014-04-01",
                "slutlev": " ",
                "varugrupp": "Grappa och Marc, Grappa",
                "forpackning": "Flaska",
                "forslutning": "",
                "ursprung": "",
                "ursprunglandnamn": "Italien",
                "producent": "Distilleria Levi Serafino ( di",
                "leverantor": "Haugen-Gruppen AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "40%",
                "modul": "",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1010404",
                "artikelid": "611864",
                "varnummer": "10104",
                "namn": "Giare 5 Grappe",
                "namn2": "Moscato, Amarone, Teroldego, Chardonnay, Prosecco",
                "prisinklmoms": "399.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2012-03-01",
                "slutlev": " ",
                "varugrupp": "Grappa och Marc, Grappa",
                "forpackning": "5 flaskor \u00c3\u00a0 100 ml",
                "forslutning": "",
                "ursprung": "",
                "ursprunglandnamn": "Italien",
                "producent": "Marzadro",
                "leverantor": "Stragas-Gruppen AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "40%",
                "modul": "",
                "sortiment": "TST",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1010501",
                "artikelid": "659534",
                "varnummer": "10105",
                "namn": "Genuin 25",
                "namn2": "",
                "prisinklmoms": "149.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2012-09-01",
                "slutlev": " ",
                "varugrupp": "Okryddad sprit",
                "forpackning": "Flaska",
                "forslutning": "Skruvkapsyl",
                "ursprung": "",
                "ursprunglandnamn": "Sverige",
                "producent": "Svensk Vodka i Motala AB",
                "leverantor": "Svensk Vodka i Motala AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "25%",
                "modul": "",
                "sortiment": "TST",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1011302",
                "artikelid": "723428",
                "varnummer": "10113",
                "namn": "Kullados",
                "namn2": "",
                "prisinklmoms": "499.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2013-04-02",
                "slutlev": " ",
                "varugrupp": "\u00c3\u2013vrig sprit",
                "forpackning": "Flaska",
                "forslutning": "Plastkork\/syntetkork",
                "ursprung": "",
                "ursprunglandnamn": "Sverige",
                "producent": "Kullabygdens Musteri AB",
                "leverantor": "Kullabygdens Destilleri AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "40%",
                "modul": "T5",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1011401",
                "artikelid": "811782",
                "varnummer": "10114",
                "namn": "Grappa Riserva Levi Romano",
                "namn2": "Distilleria Levi Serafino Donna Selvatica",
                "prisinklmoms": "989.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2014-03-01",
                "slutlev": " ",
                "varugrupp": "Grappa och Marc, Grappa",
                "forpackning": "Flaska",
                "forslutning": "Naturkork",
                "ursprung": "",
                "ursprunglandnamn": "Italien",
                "producent": "Distilleria Levi Serafino ( di",
                "leverantor": "Haugen-Gruppen AB",
                "argang": "",
                "provadargang": "",
                "alkoholhalt": "50%",
                "modul": "",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }, {
                "nr": "1011601",
                "artikelid": "614078",
                "varnummer": "10116",
                "namn": "Glenmorangie",
                "namn2": "Pride",
                "prisinklmoms": "24500.00",
                "volymiml": null,
                "prisperliter": null,
                "saljstart": "2012-02-23",
                "slutlev": " ",
                "varugrupp": "Whisky, Malt",
                "forpackning": "Flaska",
                "forslutning": "Naturkork",
                "ursprung": "Skottland, Highlands, Northern Highlands",
                "ursprunglandnamn": "Storbritannien",
                "producent": "Glenmorangie",
                "leverantor": "Mo\u00c3\u00abt Hennessy Sverige AB",
                "argang": "1981",
                "provadargang": "",
                "alkoholhalt": "56.7%",
                "modul": "",
                "sortiment": "TSE",
                "ekologisk": "0",
                "koscher": "0"
            }], 
            "wine" :
    [{
            "nr": "1201501",
            "artikelid": "10902",
            "varnummer": "12015",
            "namn": "Drostdy-Hof",
            "namn2": "Sauvignon Blanc",
            "prisinklmoms": "69.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1996-08-19",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Friskt & Fruktigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "Western Cape",
            "ursprunglandnamn": "Sydafrika",
            "producent": "Drostdy Cellars",
            "leverantor": "Bibendum",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "12%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1207401",
            "artikelid": "13650",
            "varnummer": "12074",
            "namn": "Drostdy-Hof",
            "namn2": "Chardonnay",
            "prisinklmoms": "69.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1997-07-07",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Friskt & Fruktigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "Western Cape",
            "ursprunglandnamn": "Sydafrika",
            "producent": "Drostdy Cellars",
            "leverantor": "Bibendum",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1208501",
            "artikelid": "32777",
            "varnummer": "12085",
            "namn": "Wild Strawberry Sparkling",
            "namn2": "",
            "prisinklmoms": "65.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2002-02-04",
            "slutlev": " ",
            "varugrupp": "Mousserande vin, \u00c3\u2013vrigt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Sk\u00c3\u00a5ne l\u00c3\u00a4n, Simrishamns kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "\u00c3\u2026kesson Vin AB",
            "leverantor": "Kiviks Musteri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "12%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1209408",
            "artikelid": "36202",
            "varnummer": "12094",
            "namn": "Robertson",
            "namn2": "Chardonnay",
            "prisinklmoms": "189.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2002-10-07",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Fylligt & Smakrikt",
            "forpackning": "Box",
            "forslutning": "Vridtapp",
            "ursprung": "Western Cape",
            "ursprunglandnamn": "Sydafrika",
            "producent": "Robertson Winery",
            "leverantor": "Prime Wine Sweden AB",
            "argang": "2014",
            "provadargang": "2014",
            "alkoholhalt": "13%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1209501",
            "artikelid": "35322",
            "varnummer": "12095",
            "namn": "Grythyttan Hjortron",
            "namn2": "",
            "prisinklmoms": "189.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2002-08-05",
            "slutlev": " ",
            "varugrupp": "Fruktvin, S\u00c3\u00b6tt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "\u00c3\u2013rebro l\u00c3\u00a4n, \u00c3\u2013rebro kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Grythyttan Vin AB",
            "leverantor": "Grythyttan Vin",
            "argang": "2010",
            "provadargang": "2010",
            "alkoholhalt": "13.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1209502",
            "artikelid": "732557",
            "varnummer": "12095",
            "namn": "Grythyttan Hjortron",
            "namn2": "",
            "prisinklmoms": "166.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-04-02",
            "slutlev": " ",
            "varugrupp": "Fruktvin, S\u00c3\u00b6tt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "\u00c3\u2013rebro l\u00c3\u00a4n, \u00c3\u2013rebro kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Grythyttan Vin AB",
            "leverantor": "Grythyttan Vin",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1210301",
            "artikelid": "36345",
            "varnummer": "12103",
            "namn": "JP Chenet",
            "namn2": "Colombard Sauvignon Blanc",
            "prisinklmoms": "59.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2002-09-02",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Friskt & Fruktigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Frankrike",
            "producent": "JP Chenet",
            "leverantor": "Stellan Kramer AB",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "11.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1210304",
            "artikelid": "38507",
            "varnummer": "12103",
            "namn": "JP Chenet",
            "namn2": "Colombard Sauvignon blanc",
            "prisinklmoms": "26.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2003-02-01",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Friskt & Fruktigt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Frankrike",
            "producent": "JP Chenet",
            "leverantor": "Stellan Kramer AB",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "11.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1210501",
            "artikelid": "27485",
            "varnummer": "12105",
            "namn": "Hubert Beck",
            "namn2": "R\u00c3\u00a9serve du Chevalier Pinot Gris",
            "prisinklmoms": "99.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2001-02-05",
            "slutlev": " ",
            "varugrupp": "Vitt vin,  Druvigt & Blommigt",
            "forpackning": "Flaska",
            "forslutning": "Plastkork\/syntetkork",
            "ursprung": "Alsace",
            "ursprunglandnamn": "Frankrike",
            "producent": "Hubert Beck",
            "leverantor": "Swedish Wine Cellar AB",
            "argang": "2013",
            "provadargang": "2013",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1210502",
            "artikelid": "643373",
            "varnummer": "12105",
            "namn": "Hubert Beck",
            "namn2": "R\u00c3\u00a9serve du Chevalier Pinot Gris",
            "prisinklmoms": "49.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-04-02",
            "slutlev": " ",
            "varugrupp": "Vitt vin, Torrt, Druvigt & Blo",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Alsace",
            "ursprunglandnamn": "Frankrike",
            "producent": "Hubert Beck",
            "leverantor": "Swedish Wine Cellar AB",
            "argang": "2012",
            "provadargang": "2012",
            "alkoholhalt": "12.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }], "beer" :
        [{
            "nr": "1135612",
            "artikelid": "766334",
            "varnummer": "11356",
            "namn": "Pripps Blå Julöl",
            "namn2": "",
            "prisinklmoms": "15.30",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-11-15",
            "slutlev": " ",
            "varugrupp": "Öl, Mörk lager",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "Hallands län, Falkenbergs kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Carlsberg Sverige AB",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "TSS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1140003",
            "artikelid": "190837",
            "varnummer": "11400",
            "namn": "Pripps Blå Pure",
            "namn2": "",
            "prisinklmoms": "11.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2006-04-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Hallands län, Falkenbergs kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Carlsberg Sverige AB",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "4.8%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1145103",
            "artikelid": "442400",
            "varnummer": "11451",
            "namn": "Pripps Blå",
            "namn2": "",
            "prisinklmoms": "9.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2010-03-24",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Hallands län, Falkenbergs kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Carlsberg Sverige AB",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "129603",
            "artikelid": "7096",
            "varnummer": "1296",
            "namn": "Pripps Extra Stark",
            "namn2": "",
            "prisinklmoms": "8.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1995-01-30",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Hallands län, Falkenbergs kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Carlsberg Sverige AB",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "7.2%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "158503",
            "artikelid": "1187",
            "varnummer": "1585",
            "namn": "San Miguel",
            "namn2": "",
            "prisinklmoms": "14.70",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1985-10-01",
            "slutlev": " ",
            "varugrupp": "Öl, Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Spanien",
            "producent": "San Miguel",
            "leverantor": "Brewery International Sweden A",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.4%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0"
        }, {
            "nr": "1108201",
            "artikelid": "736682",
            "varnummer": "11082",
            "namn": "Thornbridge Raven Black IPA",
            "namn2": "",
            "prisinklmoms": "39.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-04-02",
            "slutlev": " ",
            "varugrupp": "Öl, Ale",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Storbritannien",
            "producent": "Thornbridge Brewery",
            "leverantor": "Galatea Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "6.6%",
            "modul": "T5",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0"
        }]
};
